# Generated by Django 2.2.2 on 2019-07-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('access', models.CharField(max_length=5)),
                ('devices', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True)),
                ('site_name', models.CharField(max_length=40, unique=True)),
                ('device_imei', models.CharField(max_length=20)),
                ('device_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='StatusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dse_status', models.IntegerField()),
                ('dse_mode', models.IntegerField()),
                ('local_storage', models.CharField(max_length=5)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Device')),
            ],
        ),
        migrations.CreateModel(
            name='MainsLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('l1nv', models.FloatField()),
                ('l2nv', models.FloatField()),
                ('l3nv', models.FloatField()),
                ('l1l2v', models.FloatField()),
                ('l1l3v', models.FloatField()),
                ('l2l3v', models.FloatField()),
                ('l1na', models.FloatField()),
                ('l2na', models.FloatField()),
                ('l3na', models.FloatField()),
                ('frequency', models.FloatField()),
                ('backup', models.FloatField()),
                ('backup_load', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Device')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('l1nv', models.FloatField()),
                ('l2nv', models.FloatField()),
                ('l3nv', models.FloatField()),
                ('l1l2v', models.FloatField()),
                ('l1l3v', models.FloatField()),
                ('l2l3v', models.FloatField()),
                ('l1na', models.FloatField()),
                ('l2na', models.FloatField()),
                ('l3na', models.FloatField()),
                ('frequency', models.FloatField()),
                ('rpm', models.FloatField()),
                ('fuel_level', models.FloatField()),
                ('battery_voltage', models.FloatField()),
                ('alternator_voltage', models.FloatField()),
                ('temperature', models.FloatField()),
                ('run_hours', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Device')),
            ],
        ),
    ]
