# Generated by Django 2.2.2 on 2019-09-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alarms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarms',
            old_name='dg_common_fault',
            new_name='dse_emergency_stop',
        ),
        migrations.RenameField(
            model_name='alarms',
            old_name='mains_on_load',
            new_name='generator_low_voltage',
        ),
        migrations.RemoveField(
            model_name='alarms',
            name='site_on_batteries',
        ),
    ]
