# Generated by Django 3.0.6 on 2020-05-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20200219_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=150)),
                ('is_critical', models.BooleanField()),
                ('sms_sent', models.BooleanField()),
                ('email_sent', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ViewNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enable', models.BooleanField()),
                ('email_enable', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User')),
            ],
        ),
    ]
