# Generated by Django 3.0.6 on 2020-05-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_notification_notificationssettings_viewnotifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_active_state', models.CharField(max_length=8)),
                ('previous_mains_state', models.BooleanField()),
                ('previous_gen_state', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Device')),
            ],
        ),
    ]
