# Generated by Django 3.0.6 on 2020-05-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_devicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehistory',
            name='previous_gen_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='previous_mains_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationssettings',
            name='email_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationssettings',
            name='sms_enable',
            field=models.BooleanField(default=False),
        ),
    ]
