# Generated by Django 3.0.6 on 2020-05-12 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20200510_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitor.Device'),
        ),
    ]
