# Generated by Django 3.0.6 on 2020-05-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_notification_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousAlarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('dg_fail_to_start', models.BooleanField(default=False)),
                ('dg_low_fuel', models.BooleanField(default=False)),
                ('dg_battery_low', models.BooleanField(default=False)),
                ('charging_alt_fail', models.BooleanField(default=False)),
                ('ac_mains_fail', models.BooleanField(default=False)),
                ('high_coolant_temp', models.BooleanField(default=False)),
                ('dse_emergency_stop', models.BooleanField(default=False)),
                ('generator_low_voltage', models.BooleanField(default=False)),
                ('charge_alt_error', models.BooleanField(default=False)),
                ('dse_disconnected', models.BooleanField(default=False)),
                ('site_state', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Device', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='viewnotifications',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='viewnotifications',
            name='user',
        ),
        migrations.AddField(
            model_name='notificationssettings',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationssettings',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='DeviceHistory',
        ),
        migrations.DeleteModel(
            name='ViewNotifications',
        ),
    ]
