# Generated by Django 3.0.6 on 2020-05-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20200523_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousalarms',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.Device'),
        ),
    ]
