# Generated by Django 3.0.6 on 2020-05-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20200523_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.Device')),
            ],
        ),
    ]
