# Generated by Django 3.0.6 on 2020-06-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_devicesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationssettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.User'),
        ),
    ]
